### PR TITLE
Added a link to javanese.online repo

### PR DESCRIPTION
**Pull request by Miha-x64**

### CODE REVIEW

**Comment by orangy** [comment]
I think it should link to "https://github.com/JavaneseOnline/JavaneseBackend" since the section is about OSS usages of the framework.

**Comment by Miha-x64** [comment]
It links to exactly that place. :)

**Comment by orangy** [comment]
Ah, sorry, I copy/pasted wrong part of the markdown :) And it worked!

**Comment by soywiz** [comment]
Since the documentation is in english, I would append the language to links in other languages so the people is aware of the language change. What do you think?
Something like: `* [Javanese.Online](https://github.com/JavaneseOnline/JavaneseBackend) *(Russian)*`

**Comment by Miha-x64** [comment]
Of course, looks reasonable. (...but all KDocs are in English)

**Comment by soywiz** [comment]
Okay, thanks! :)

I said that because of the readme file that is what people see first and gives an overview of the project. But since it is for a website in russian makes sense to be written in russian. Maybe a mixed approach would be to put a small section in the readme in english too explaining what the project is? Still not a big deal :)

**Comment by Miha-x64** [comment]
Translated readme into English.

**Pull request merged**
