### PR TITLE
Add Gradle Kotlin DSL samples #78

### PR DESCRIPTION
**Pull request by IRus**

### CODE REVIEW

**Comment by IRus** [comment]
@soywiz can you review this changes, before I started converting this files?:

- [ ] servers/deploy
- [ ] servers/self-signed-certificate
- [ ] quickstart/docker
- [ ] quickstart/gradle

**Comment by soywiz** [comment]
Looks good to me.

Though maybe would be nice to put those in an `_include` file in a way that generates code so people can select with tabs either Groovy, Kotlin DSL (or Maven when relevant).

Since the Kotlin DSL is not 1.0 yet, most of the scripts are still groovy and could confuse people that has just started.
Once it is mainstream we could change the default tab to Kotlin DSL, and eventually simplify to just Kotlin DSL.

**Comment by IRus** [comment]
Not sure if it make sense to combine gradle and maven under same tabs, because structure of build scripts can be very different. 

I already put in `_inculde` template `gradle.html`, and yes, it usage not perfect:

```
{% capture gradle-kotlin-build %}
// build.gradle.kts code here
{% endcapture %}

{% capture gradle-groovy-build %}
// build.gradle code hjere
{% endcapture %}

add tabs:
{% include gradle.html gradle-kotlin=gradle-kotlin-build gradle-groovy=gradle-groovy-build %}
```

So it looks like:

image

Do you know how to do it in better way?

**Comment by IRus** [comment]
Ah, yes, I can add another tab for **kotlin dsl**, but actually there are common way for defining deps both in kotlin dsl and groovy:

```
dependencies {
    compile("group:name:$version")
}
```

I already did this changes, maybe some clarification needed that this snippet works in kotlin and groovy?

**Comment by soywiz** [comment]
Not sure if tab title `Gradle (Groovy/Kotlin)` would be too long. Maybe a small paragraph with something like `This snippet works with both: Groovy and Kotlin-DS. With groovy, the parenthesis are optional.`
The only problem that I see with using the same for both, is that some people might mix parenthesis without parenthesis when copy-pasting in their scripts. A minor issue, but still.
But don't worry too much. I guess I can add a javascript or something later with a checkbox for selecting the preferred style or something and keep it between requests. if required.

**Comment by IRus** [comment]
Maybe then better to add another tab? It's small, simple change and snippets looks cleaner (from my pov):

image
image

**Comment by soywiz** [comment]
Is this ready?

**Comment by IRus** [comment]
Yes and no. I'm actually not converted few files mentioned early, but It
can be done as separate PR.

**Comment by soywiz** [comment]
Okay. Let's include it in a separate PR.

**Comment by IRus** [comment]
Thanks, I think I'll convert rest of files after KotlinConf.

**Pull request merged**
